// Generated by commsdsl2tools_qt v6.3.2

#pragma once

#include <QtCore/QVariantList>
#include "cc_demo3/message/Msg1.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt_plugin/cc_demo3/Message.h"
#include "cc_tools_qt_plugin/cc_demo3/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

namespace message
{

class Msg1 : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_demo3::message::Msg1<cc_tools_qt_plugin::cc_demo3::Message, cc_tools_qt_plugin::cc_demo3::options::DefaultOptions>,
        Msg1
    >
{
public:
    Msg1();
    Msg1(const Msg1&) = delete;
    Msg1(Msg1&&) = delete;
    virtual ~Msg1();
    Msg1& operator=(const Msg1&);
    Msg1& operator=(Msg1&&);

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace message

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
