// Generated by commsdsl2tools_qt v7.0.0

#include "MsgFactory.h"

#include "cc_tools_qt_plugin/Message/cc_demo3/message/Connect.h"
#include "cc_tools_qt_plugin/Message/cc_demo3/message/Msg1.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo3
{

namespace factory
{

MsgFactory::MsgFactory() = default;
MsgFactory::~MsgFactory() = default;

MsgFactory::MessagesListInternal MsgFactory::createAllMessagesImpl()
{
    return
        MessagesListInternal{
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_demo3::message::Connect),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_demo3::message::Msg1)
        };
}

} // namespace factory

} // namespace cc_demo3

} // namespace Message

} // namespace cc_tools_qt_plugin
