// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include <tuple>
#include "cc_tools_qt_plugin/cc_demo3/message/Connect.h"
#include "cc_tools_qt_plugin/cc_demo3/message/Msg1.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

namespace input
{

using AllMessages =
    std::tuple<
        cc_tools_qt_plugin::cc_demo3::message::Connect,
        cc_tools_qt_plugin::cc_demo3::message::Msg1
    >;

} // namespace input

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
