// Generated by commsdsl2tools_qt v6.3.4

#include "FrameTransportMessage.h"

#include "cc_demo3/field/MsgId.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_demo3/field/MsgId.h"
#include "cc_tools_qt_plugin/cc_demo3/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

namespace frame
{

struct SyncLayer
{
    static QVariantMap createProps_sync(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_demo3::frame::FrameLayers<cc_tools_qt_plugin::cc_demo3::options::DefaultOptions>::SyncMembers::Sync;
        return
            cc_tools_qt::property::field::ForField<Field>()
                .name(Field::name())
                .serialisedHidden(serHidden)
                .asMap();
    }
}; // struct SyncLayer

struct SizeLayer
{
    static QVariantMap createProps_size(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_demo3::frame::FrameLayers<cc_tools_qt_plugin::cc_demo3::options::DefaultOptions>::SizeMembers::Size;
        return
            cc_tools_qt::property::field::ForField<Field>()
                .name(Field::name())
                .serialisedHidden(serHidden)
                .displayOffset(2)
                .asMap();
    }
}; // struct SizeLayer

struct IdLayer
{
    static QVariantMap createProps_msgId(bool serHidden)
    {
        return cc_tools_qt_plugin::cc_demo3::field::createProps_msgId("MsgId", serHidden);
    }
}; // struct IdLayer

struct VersionLayer
{
    static QVariantMap createProps_version(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_demo3::frame::FrameLayers<cc_tools_qt_plugin::cc_demo3::options::DefaultOptions>::VersionMembers::Version;
        return
            cc_tools_qt::property::field::ForField<Field>()
                .name(Field::name())
                .serialisedHidden(serHidden)
                .asMap();
    }
}; // struct VersionLayer

struct DataLayer
{
    static QVariantMap createProps_data(bool serHidden)
    {
        return cc_tools_qt::property::field::ArrayList().name("Data").serialisedHidden(serHidden).asMap();
    }
}; // struct DataLayer

struct ChecksumLayer
{
    static QVariantMap createProps_checksum(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_demo3::frame::FrameLayers<cc_tools_qt_plugin::cc_demo3::options::DefaultOptions>::ChecksumMembers::Checksum;
        return
            cc_tools_qt::property::field::ForField<Field>()
                .name(Field::name())
                .serialisedHidden(serHidden)
                .asMap();
    }
}; // struct ChecksumLayer

namespace
{

QVariantList createProps()
{
     QVariantList props;
     props.append(SyncLayer::createProps_sync(false));
     props.append(SizeLayer::createProps_size(false));
     props.append(IdLayer::createProps_msgId(false));
     props.append(VersionLayer::createProps_version(true));
     props.append(DataLayer::createProps_data(false));
     props.append(ChecksumLayer::createProps_checksum(false));
     return props;
}

} // namespace

const QVariantList& FrameTransportMessageFields::props()
{
    static const QVariantList Props = createProps();
    return Props;
}

const QVariantList& FrameTransportMessage::fieldsPropertiesImpl() const
{
    return FrameTransportMessageFields::props();
}

comms::ErrorStatus FrameTransportMessage::readImpl(ReadIterator& iter, std::size_t len)
{
    len -= 2U;
    auto es = doReadUntilAndUpdateLen<5U>(iter, len);
    if (es == comms::ErrorStatus::Success) {
        len += 2U;
        es = doReadFrom<5U>(iter, len);
    }

    return es;
}

} // namespace frame

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
