// Generated by commsdsl2tools_qt v7.1.0

#include "Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo3
{

Message::Message() = default;

Message::~Message() noexcept = default;

} // namespace cc_demo3

} // namespace Message

} // namespace cc_tools_qt_plugin
