// Generated by commsdsl2tools_qt v6.3.2

#include "Plugin_CC_Demo3.h"

#include "Protocol_CC_Demo3.h"

#include "ConfigWidget_CC_Demo3.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

namespace plugin
{

Plugin_CC_Demo3::Plugin_CC_Demo3() :
    m_protocol(new Protocol_CC_Demo3())
{
    pluginProperties()
        .setProtocolCreateFunc(
            [this]() noexcept -> cc_tools_qt::ProtocolPtr
            {
                return m_protocol;
            })
        .setConfigWidgetCreateFunc(
            [this]() -> QWidget*
            {
                auto* w =
                    new ConfigWidget_CC_Demo3(
                        static_cast<Protocol_CC_Demo3*>(m_protocol.get())->getVersion());
                w->setVersionUpdateCb(
                    [this](int value) {
                        static_cast<Protocol_CC_Demo3*>(m_protocol.get())->setVersion(value);
                    });
                return w;
            })

    ;
}

Plugin_CC_Demo3::~Plugin_CC_Demo3() = default;

} // namespace plugin

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
