// Generated by commsdsl2tools_qt v7.1.0

#include "Protocol_CC_Demo3.h"

#include "cc_tools_qt_plugin/Message/cc_demo3/frame/Frame.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

namespace plugin
{

Protocol_CC_Demo3::Protocol_CC_Demo3() :
    Base(std::make_unique<cc_tools_qt_plugin::Message::cc_demo3::frame::Frame>())
{
}

Protocol_CC_Demo3::~Protocol_CC_Demo3() = default;

const QString& Protocol_CC_Demo3::nameImpl() const
{
        static const QString Str("CC Demo3");
        return Str;
}

} // namespace plugin

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
