// Generated by commsdsl2tools_qt v6.3.4

#pragma once

#include "cc_demo3/Message.h"
#include "cc_tools_qt/MessageBase.h"
#include "cc_tools_qt_plugin/cc_demo3/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo3
{

class Message : public
    cc_tools_qt::MessageBase<
        ::cc_demo3::Message
    >
{
protected:
    virtual const QVariantList& extraTransportFieldsPropertiesImpl() const override;
};

} // namespace cc_demo3

} // namespace cc_tools_qt_plugin
